### ISSUE TITLE
Punthulhu's github alt // Emojis not automatically removed.

### ISSUE THREAD

**Issue by Cephalopod08** [qpn6ph9q/discomod-tracker#10]
Seems if you add more than 1 emoji to filter, they do not work at all.

**Comment by qpn6ph9q** [comment]
Linking with #7

**Comment by qpn6ph9q** [comment]
This was fixed in https://github.com/qpn6ph9q/discomod/commit/727f10a6d311affcc1874ff8cc7e2802fbcd68c9
