### ISSUE TITLE
New message popup 

### ISSUE THREAD

**Issue by AlluringSecret** [qpn6ph9q/discomod-tracker#30]
New messages briefly cause the grey new message pop up bar to appear. Very uncomfortable flashing 
https://gyazo.com/43e80b1bce179fa03b1c3ec918c0ddb7

**Comment by Cemmos** [comment]
Seems to be due to new messages temporarily pushing the scrollbar up, then it pops back down.

**Comment by qpn6ph9q** [comment]
Fixed in https://github.com/qpn6ph9q/discomod/commit/e1092d03cf2181b30ff6437ec663b336aa01ea2d
