### ISSUE TITLE
Suggestion: Autospam log should provide context of posts preceding triggering post

### ISSUE THREAD

**Issue by Greypelt** [qpn6ph9q/discomod-tracker#35]
it looks like autospam was triggered for a message consisting of '3' ?
I assume that was part of a chain of like
1
2
3
or something
would be nice if the log gave more context as to what triggered the autospam, aka like x msgs before it also being listed
I've left some relevant private reference photos in another location

**Comment by qpn6ph9q** [comment]
I have updated the guidelines to show the various automod codes. In addition the flood filter is configured in a particular way but im not sure if I am permitted to release those details. I'll check :)
